module OrdnanceSurveyHelpers
  def stub_search_places_index(claim:)
    args = {
      query: WebMock::API.hash_including(
        {
          postcode: "SO169FX",
          key: "api-key-value",
          maxresults: 1
        }
      ),
      body: {
        results: [
          {
            DPA: {
              UPRN: "100062039919",
              UDPRN: "22785699",
              ADDRESS: "FLAT 1, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 1",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039928",
              UDPRN: "22785700",
              ADDRESS: "FLAT 10, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 10",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039929",
              UDPRN: "22785701",
              ADDRESS: "FLAT 11, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 11",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039930",
              UDPRN: "22785702",
              ADDRESS: "FLAT 12, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 12",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039931",
              UDPRN: "22785703",
              ADDRESS: "FLAT 13, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 13",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039932",
              UDPRN: "22785704",
              ADDRESS: "FLAT 14, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 14",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039933",
              UDPRN: "22785705",
              ADDRESS: "FLAT 15, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 15",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039934",
              UDPRN: "22785706",
              ADDRESS: "FLAT 16, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 16",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039935",
              UDPRN: "22785707",
              ADDRESS: "FLAT 17, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 17",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039936",
              UDPRN: "22785708",
              ADDRESS: "FLAT 18, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 18",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039937",
              UDPRN: "22785709",
              ADDRESS: "FLAT 19, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 19",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039920",
              UDPRN: "22785710",
              ADDRESS: "FLAT 2, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 2",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039938",
              UDPRN: "22785711",
              ADDRESS: "FLAT 20, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 20",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039939",
              UDPRN: "22785712",
              ADDRESS: "FLAT 21, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 21",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039940",
              UDPRN: "22785713",
              ADDRESS: "FLAT 22, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 22",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039941",
              UDPRN: "22785714",
              ADDRESS: "FLAT 23, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 23",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039942",
              UDPRN: "22785715",
              ADDRESS: "FLAT 24, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 24",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039943",
              UDPRN: "22785716",
              ADDRESS: "FLAT 25, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 25",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039944",
              UDPRN: "22785717",
              ADDRESS: "FLAT 26, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 26",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039945",
              UDPRN: "22785718",
              ADDRESS: "FLAT 27, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 27",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039946",
              UDPRN: "22785719",
              ADDRESS: "FLAT 28, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 28",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039947",
              UDPRN: "22785720",
              ADDRESS: "FLAT 29, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 29",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039921",
              UDPRN: "22785721",
              ADDRESS: "FLAT 3, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 3",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039948",
              UDPRN: "22785722",
              ADDRESS: "FLAT 30, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 30",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039949",
              UDPRN: "22785723",
              ADDRESS: "FLAT 31, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 31",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039950",
              UDPRN: "22785724",
              ADDRESS: "FLAT 32, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 32",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039951",
              UDPRN: "22785725",
              ADDRESS: "FLAT 33, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 33",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039952",
              UDPRN: "22785726",
              ADDRESS: "FLAT 34, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 34",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039953",
              UDPRN: "22785727",
              ADDRESS: "FLAT 35, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 35",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039954",
              UDPRN: "22785728",
              ADDRESS: "FLAT 36, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 36",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039955",
              UDPRN: "22785729",
              ADDRESS: "FLAT 37, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 37",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039956",
              UDPRN: "22785730",
              ADDRESS: "FLAT 38, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 38",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039957",
              UDPRN: "22785731",
              ADDRESS: "FLAT 39, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 39",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039922",
              UDPRN: "22785732",
              ADDRESS: "FLAT 4, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 4",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039958",
              UDPRN: "22785733",
              ADDRESS: "FLAT 40, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 40",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039959",
              UDPRN: "22785734",
              ADDRESS: "FLAT 41, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 41",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039960",
              UDPRN: "22785735",
              ADDRESS: "FLAT 42, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 42",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039961",
              UDPRN: "22785736",
              ADDRESS: "FLAT 43, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 43",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039962",
              UDPRN: "22785737",
              ADDRESS: "FLAT 44, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 44",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039963",
              UDPRN: "22785738",
              ADDRESS: "FLAT 45, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 45",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039964",
              UDPRN: "22785739",
              ADDRESS: "FLAT 46, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 46",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039965",
              UDPRN: "22785740",
              ADDRESS: "FLAT 47, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 47",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039966",
              UDPRN: "22785741",
              ADDRESS: "FLAT 48, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 48",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039967",
              UDPRN: "22785742",
              ADDRESS: "FLAT 49, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 49",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039923",
              UDPRN: "22785743",
              ADDRESS: "FLAT 5, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 5",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039968",
              UDPRN: "22785744",
              ADDRESS: "FLAT 50, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 50",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039924",
              UDPRN: "22785745",
              ADDRESS: "FLAT 6, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 6",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039925",
              UDPRN: "22785746",
              ADDRESS: "FLAT 7, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 7",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039926",
              UDPRN: "22785747",
              ADDRESS: "FLAT 8, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 8",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          },
          {
            DPA: {
              UPRN: "100062039927",
              UDPRN: "22785748",
              ADDRESS: "FLAT 9, MILLBROOK TOWER, WINDERMERE AVENUE, SOUTHAMPTON, SO16 9FX",
              SUB_BUILDING_NAME: "FLAT 9",
              BUILDING_NAME: "MILLBROOK TOWER",
              THOROUGHFARE_NAME: "WINDERMERE AVENUE",
              POST_TOWN: "SOUTHAMPTON",
              POSTCODE: "SO16 9FX",
              RPC: "2",
              X_COORDINATE: 438092.0,
              Y_COORDINATE: 114637.0,
              STATUS: "APPROVED",
              LOGICAL_STATUS_CODE: "1",
              CLASSIFICATION_CODE: "RD06",
              CLASSIFICATION_CODE_DESCRIPTION: "Self Contained Flat (Includes Maisonette / Apartment)",
              LOCAL_CUSTODIAN_CODE: 1780,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "SOUTHAMPTON",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "2",
              BLPU_STATE_CODE_DESCRIPTION: "In use",
              TOPOGRAPHY_LAYER_TOID: "osgb1000016364569",
              PARENT_UPRN: "100062691379",
              LAST_UPDATE_DATE: "12/11/2018",
              ENTRY_DATE: "03/05/2001",
              BLPU_STATE_DATE: "11/12/2007",
              LANGUAGE: "EN",
              MATCH: 1.0,
              MATCH_DESCRIPTION: "EXACT"
            }
          }
        ]
      },
      status: 200
    }

    stub_request(:get, "https://api.os.uk/search/places/v1/postcode?key=api-key-value&postcode=SO169FX")
      .with(
        headers: {
          "Content-Type" => "application/json",
          "Expect" => "",
          "User-Agent" => "Typhoeus - https://github.com/typhoeus/typhoeus"
        }
      )
      .to_return(
        status: 200,
        body: args[:body].to_json,
        headers: {}
      )
  end

  def stub_search_places_show(claim:)
    args = {
      query: WebMock::API.hash_including(
        {
          query: "19, BD73BE",
          key: "api-key-value",
          maxresults: 1
        }
      ),
      body: {
        results: [
          {
            DPA: {
              UPRN: "100051230006",
              UDPRN: "1593790",
              ADDRESS: "19, TURNER PLACE, BRADFORD, BD7 3BE",
              BUILDING_NUMBER: "19",
              THOROUGHFARE_NAME: "TURNER PLACE",
              POST_TOWN: "BRADFORD",
              POSTCODE: "BD7 3BE",
              RPC: "1",
              X_COORDINATE: 414965.0,
              Y_COORDINATE: 432199.0,
              STATUS: "HISTORICAL",
              LOGICAL_STATUS_CODE: "8",
              CLASSIFICATION_CODE: "RD04",
              CLASSIFICATION_CODE_DESCRIPTION: "Terraced",
              LOCAL_CUSTODIAN_CODE: 4705,
              LOCAL_CUSTODIAN_CODE_DESCRIPTION: "BRADFORD MDC",
              POSTAL_ADDRESS_CODE: "D",
              POSTAL_ADDRESS_CODE_DESCRIPTION: "A record which is linked to PAF",
              BLPU_STATE_CODE: "4",
              BLPU_STATE_CODE_DESCRIPTION: "No longer existing",
              TOPOGRAPHY_LAYER_TOID: "osgb1000031905429",
              LAST_UPDATE_DATE: "11/05/2019",
              ENTRY_DATE: "05/04/2001",
              BLPU_STATE_DATE: "07/05/2019",
              LANGUAGE: "EN",
              MATCH: 0.4,
              MATCH_DESCRIPTION: "NO MATCH"
            }
          }
        ]
      },
      status: 200
    }

    stub_request(:get, "https://api.os.uk/search/places/v1/find?key=api-key-value&maxresults=1&query=19, BD73BE")
      .with(
        headers: {
          "Content-Type" => "application/json",
          "Expect" => "",
          "User-Agent" => "Typhoeus - https://github.com/typhoeus/typhoeus"
        }
      )
      .to_return(
        status: 200,
        body: args[:body].to_json,
        headers: {}
      )
  end
end
